# Name of your Slack (Deprecated in favour of the slack_name env var)
slack_name: IDEO

# Name of environment variable that determines if destalinator should
# actually do things to a live slack. Without this environment variable,
# everything will output in a "dry run" fashion (debug messages should take place,
# but no changes or messages should affect a live Slack).
activated: false

# What should the bot's name be when it posts?
bot_name: "destalinator"

# What should the bot's avatar be when it posts?
bot_avatar_url: "https://s3-us-west-1.amazonaws.com/eng-management-docs/bread.png"

# Days of silence before we warn a channel it's going to be archived
warn_threshold: 30

# Days of silence before we auto-archive a channel
archive_threshold: 60

# Where should we post "general" announcement messages?
general_message_channel: "ideo-destalinator"

# Where should we announce new channels?
announce_channel: "ideo-destalinator"

# Where do we send control messages?
control_channel: "ideo-destalinator"

# Where to send destalinator debug logs
log_channel: "ideo-destalinator"

# Channels to ignore when archiving (i.e. they can be silent and not get archived)
ignore_channels:
  - ideo-all

# Regular expression patterns for additional channels to ignore during archiving
ignore_channel_patterns: []

# Users to ignore when considering if a channel is stale
ignore_users: []

# Which message subtypes count as activity?
# "None" means the message was typed by a human and is included by default.
included_subtypes:
  - bot_message
  - channel_name
  - channel_purpose
  - channel_topic
  - file_mention
  - file_share
  - me_message
  - message_replied
  - reply_broadcast
  - slackbot_response

# When should destalinator run?
schedule_hour: 4

test_schedule: true